app1/urls.py
from django.urls import path
from app1 import views

app_name='app1'
urlpatterns=[
   path('Samsung',views.Samsung,name='Samsung'),
]

app2/urls.py
from django.urls import path
from app2 import views

app_name='app2'
urlpatterns=[ 
    path('Apple',views.Apple,name='Apple'),
    path('Realme',views.Realme,name='Realme'),
    path('oneplus',views.oneplus,name='oneplus'),
]

sunday/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('app1/',include('app1.urls',namespace='app1')),
    path('app2/',include('app2.urls',namespace='app2')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from multiprocessing import context


def home(request):
    context={'msg':'Please select the Brand'}
    return render(request,'app1/home.html',context)

def Samsung(request):
    Products=['Samsung Pocket','Samsung F20','Samsung M21','Samsung J1','Samsung J2','Samsung J5','Samsung J7']
    context={'Products': Products}
    return render(request,'app1/samsung.html',context)

# Create your views here.

app2/views.py
from django.shortcuts import render
from multiprocessing import context

def Apple(request):
    Products=['iPhone 1','iPhone 2','iPhone 7','iPhone 11','iPhone 12','iPhone 13','iPhone 13 pro','iPhone 13 pro max']
    context={'Products': Products}
    return render(request,'app2/Apple.html',context)

def Realme(request):
    Products=['Realme C1','Realme C2','Realme c3','Realme C7','Realme 5','Realme 5s','Realme C21']
    context={'Products': Products}
    return render(request,'app2/Realme.html',context)

# Create your views here.
def oneplus(request):
    Products=['oneplus2','oneplus3','oneplus5','oneplus5T','oneplus6','oneplus8','oneplus9t','oneplus10']
    context={'Products': Products}
    return render(request,'app2/oneplus.html',context)

templates/app1/Samsung.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
<img width="300" height="200" src="{% static 'images/Samsung.jpg' %}" alt="">
{% for i in Products %}
        <h2>{{i}}</h2>
{% endfor %}
{% endblock %}

templates/app1/home.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
<img src="{% static 'images/mobiles.jpg' %}" alt="">
<h2>Select above brands for movile options</h2>
{% endblock %}

templates/app2/Apple.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
<img width="300" height="150" src="{% static 'images/iPhone.png' %}" alt="">
{% for i in Products %}
        <h2>{{i}}</h2>
{% endfor %}
{% endblock %}

templates/app2/Realme.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
<img src="{% static 'images/Realme.png' %}" alt="">
{% for i in Products %}
        <h2>{{i}}</h2>
{% endfor %}
{% endblock %}

templates/app2/oneplus.html
{% extends 'base.html' %}
{% load static %}
{% block b1 %}
<img width="300" height="150" src="{% static 'images/oneplus2.png' %}" alt="">
{% for i in Products %}
        <h2>{{i}}</h2>
{% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}Dhanraj Icecreams</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Welcome to the Mobile Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app1:Samsung' %}">Samsung <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app2:Apple' %}">Apple</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app2:Realme' %}">realme</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app2:oneplus' %}">OnePlus</a>
              </li>
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
{% block body %}{% endblock body %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body><div>
    <div class="c1">
        <h1>Welcome to the Mobile Store</h1>
    </div>
   
    <div class="c2">
        {% block b1 %}
        {% endblock %}

</div>
<div>
    <div style="text-align:center;" class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Thanks for coming</h1>
          <p class="lead">Visit Again</p>
        </div>
      </div>
</div>
    
</body>
</html>